### PR TITLE
Added various nodes to the programme

### PR DESCRIPTION
**Pull request by kubaw3f**
Added:
@maxhodl:matrix.org 2 nodes
@kusamabasedot:matrix.org 2 nodes
@vita567:matrix.org 1 node
@primapolkadot:matrix.org 2 nodes
@vixy:matrix.org 2 nodes
@connectify:matrix.org 2 nodes
@ksmkvnode:matrix.org 2 nodes
@winterspring:matrix.org 1 node
@raidani:matrix.org 2 nodes
@bitdash:matrix.org 2 nodes
@garciaprod:matrix.org 2 nodes
@s.stegno:matrix.org 1 node
@panda_warrior:matrix.org 1 node
@alko989:matrix.org 1 node
@tentbakers:matrix.org 1 node

Updated KYC:
@cristi_an_m:matrix.org

### CODE REVIEW

**Comment by kubaw3f** [comment]
@ironoa Element handles wereof the users were verified

**Review by kubaw3f — COMMENTED** [review]
Updated KYC
@staking4all:matrix.org

**Review by kubaw3f — COMMENTED** [review]
Added 1 node:
@eagle-node:matrix.org

@ironoa Element user was verified

**Comment by ironoa** [comment]
@kubaw3f 

image

image

**Review by ironoa — APPROVED** [review]

**Pull request merged**
